### ISSUE TITLE
[3pts] Set up Kanban board

### ISSUE THREAD

**Issue by VTY1999** [VTY1999/Ruby-group-capstone#17]
Set up kanban board and assigned roles to each team member
The number of team members:

1. @Kandy-Peter
2. @BereketRetta
3. @zieeco 
4. @VTY1999  

This is the link to the [Project](https://github.com/VTY1999/Ruby-group-capstone/projects/1)

**Comment by t-yanick** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments below._

- [ ] Please make sure your GitHub usernames are assigned to: `Team member #1`, `Team member #2`, `Team member #3`,  `Team member #4` as this will facilitate the distribution of tasks.
- [ ] Please make sure the tasks are distributed to the team members as specified in the project [requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md), that is the person who is `Team member #1` should be assigned the tasks under `Team member #1` as per project requirements. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi team,

Your project is complete!  There is nothing else to say other than... it's time to go ahead with your project :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
